"""update Playlist.owner_id foreign key value

Revision ID: 3c51ca118572
Revises: cac2b7b6009b
Create Date: 2022-10-30 15:28:16.534701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c51ca118572'
down_revision = 'cac2b7b6009b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    naming_convention = {
        'fk':
        'fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s'
    }
    with op.batch_alter_table('playlist', naming_convention=naming_convention, schema=None) as batch_op:
        batch_op.drop_constraint('fk_playlist_owner_id_owner', type_='foreignkey')
        batch_op.create_foreign_key('fk_playlist_owner_id_owner', 'owner', ['owner_id'], ['spotify_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.drop_constraint('owner_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_playlist_owner_id_owner', 'owner', ['owner_id'], ['id'])

    # ### end Alembic commands ###
