"""initial migration actually with models

Revision ID: d13e248cb5d8
Revises: 
Create Date: 2022-10-26 21:11:44.543798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13e248cb5d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_id')
    )
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.VARCHAR(length=128), nullable=False),
    sa.Column('email_address', sa.VARCHAR(length=128), nullable=True),
    sa.Column('instagram_handle', sa.VARCHAR(length=128), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('email_address', sa.VARCHAR(length=256), nullable=False),
    sa.Column('password', sa.VARCHAR(length=256), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.VARCHAR(length=300), nullable=True),
    sa.Column('url', sa.VARCHAR(length=128), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_id')
    )
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('popularity', sa.SMALLINT(), nullable=True),
    sa.Column('artist_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.spotify_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_id')
    )
    op.create_table('usage_statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('artists', sa.JSON(), nullable=False),
    sa.Column('songs', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_in_playlist',
    sa.Column('playlist_id', sa.String(length=40), nullable=True),
    sa.Column('song_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.spotify_id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.spotify_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_in_playlist')
    op.drop_table('usage_statistic')
    op.drop_table('song')
    op.drop_table('playlist')
    op.drop_table('user')
    op.drop_table('owner')
    op.drop_table('artist')
    # ### end Alembic commands ###
